name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt
            setup.py

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml',
           '**/requirements*.txt',
            '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --cache-dir ~/.cache/pip pytest pytest-cov coverage
          pip install --cache-dir ~/.cache/pip -e .[dev,test] || \
            pip install --cache-dir ~/.cache/pip -e .

      - name: Test with pytest and coverage
        run: |
          pytest --cov=. \
            --cov-report=xml \
            --cov-report=term-missing
