---
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage
          # Install project dependencies from pyproject.toml
          pip install -e .[dev,test] || pip install -e .
      - name: Test with pytest and coverage
        run: |
          pytest --cov=. \
            --cov-report=xml \
            --cov-report=term-missing
